plugins {
    id 'com.android.application'
}

android {
    namespace 'com.daniel.dnsoneclick'
    compileSdk 35

    defaultConfig {
        applicationId 'com.daniel.dnsoneclick'
        minSdk 30
        targetSdk 35
        versionCode 3
        versionName '1.1.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.github.MuntashirAkon:libadb-android:3.1.1'
    implementation 'com.github.MuntashirAkon:sun-security-android:1.1'
    implementation 'org.conscrypt:conscrypt-android:2.5.3'
}
